app_manager:
    type: rest
    prefix: /api
    resource: "@ManagerBundle/Resources/config/routes.yml"
    defaults: {_format: json}

# app/config/routing.yml
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc